apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-web
  template:
    metadata:
      labels:
        app: capstone-web
    spec:
      containers:
      - name: capstone-web
        image: valmikiops/capstoneweb:0.2
        ports:
        - containerPort: 3000
        env:
        - name: APPNAME
          value: "My Awesome Capstone App"
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-web-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30007
  selector:
    app: capstone-web